/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Challenge */
        post: operations["request_challenge_api_v1_auth_challenges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        /** Logout */
        delete: operations["logout_api_v1_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest-dispatches/{dispatch_public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dispatch */
        get: operations["dispatch_api_v1_ingest_dispatches__dispatch_public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_library_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_library_items__item_public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_library_items__item_public_id__patch"];
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transcript Page */
        get: operations["transcript_page_api_v1_library_items__item_public_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}:archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive */
        post: operations["archive_api_v1_library_items__item_public_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}:restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore */
        post: operations["restore_api_v1_library_items__item_public_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items/{item_public_id}:retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_library_items__item_public_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/items:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Batch */
        post: operations["save_batch_api_v1_library_items_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchItemResponse */
        BatchItemResponse: {
            /** Input Index */
            input_index: number;
            /** Item Public Id */
            item_public_id?: string | null;
            /** Lifecycle */
            lifecycle?: ("archived" | "ready" | "needs_action" | "failed" | "processing" | "queued") | null;
            /** Result Id */
            result_id: string;
            /** Safe Error Code */
            safe_error_code?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "already_exists" | "unsupported_url" | "invalid_url" | "queue_unavailable" | "create_failed" | "quota_exceeded";
        };
        /** BatchSaveRequest */
        BatchSaveRequest: {
            /** Urls */
            urls: string[];
            /** Why Saved */
            why_saved?: string | null;
        };
        /** BatchSaveResponse */
        BatchSaveResponse: {
            /** Results */
            results: components["schemas"]["BatchItemResponse"][];
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /**
             * Archive
             * @default true
             */
            archive: boolean;
            /**
             * Chat
             * @default false
             */
            chat: boolean;
            /**
             * Max Save Batch Size
             * @default 10
             */
            max_save_batch_size: number;
            /**
             * Save Enabled
             * @default true
             */
            save_enabled: boolean;
            /**
             * Summary Generation
             * @default false
             */
            summary_generation: boolean;
            /**
             * Supported Platforms
             * @default [
             *       "youtube"
             *     ]
             */
            supported_platforms: "youtube"[];
            /**
             * Transcript Pagination
             * @default true
             */
            transcript_pagination: boolean;
            /**
             * Web Login Channels
             * @default [
             *       "telegram",
             *       "wechat"
             *     ]
             */
            web_login_channels: ("email" | "telegram" | "wechat")[];
        };
        /**
         * ChapterResponse
         * @description Normalized public subset of connector-provided chapter metadata.
         */
        ChapterResponse: {
            /** End */
            end?: number | null;
            /** End Sec */
            end_sec?: number | null;
            /** End Time */
            end_time?: number | null;
            /** Start */
            start?: number | null;
            /** Start Sec */
            start_sec?: number | null;
            /** Start Time */
            start_time?: number | null;
            /** Title */
            title?: string | null;
        };
        /** DispatchResponse */
        DispatchResponse: {
            /** Attempt */
            attempt: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Item Public Id */
            item_public_id: string;
            /** Public Id */
            public_id: string;
            /** State */
            state: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EmailChallengeRequest */
        EmailChallengeRequest: {
            /** Email */
            email: string;
        };
        /** EmailSessionResponse */
        EmailSessionResponse: {
            /**
             * Authenticated
             * @default true
             */
            authenticated: boolean;
            /** Expires At */
            expires_at: string;
            /**
             * Login Channel
             * @default email
             * @constant
             */
            login_channel: "email";
            /** Tenant */
            tenant: {
                [key: string]: number;
            };
        };
        /** EmailVerifyRequest */
        EmailVerifyRequest: {
            /** Code */
            code: string;
            /** Email */
            email: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LibraryItemResponse */
        LibraryItemResponse: {
            /** Author */
            author: string | null;
            /** Available Actions */
            available_actions: string[];
            /** Chapters */
            chapters: components["schemas"]["ChapterResponse"][];
            /** Cover Url */
            cover_url: string | null;
            /** Description */
            description: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Error Code */
            error_code: string | null;
            /** Kind */
            kind: string;
            /** Lang */
            lang: string | null;
            /** Latest Dispatch Public Id */
            latest_dispatch_public_id: string | null;
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "archived" | "ready" | "needs_action" | "failed" | "processing" | "queued";
            /** Platform */
            platform: string;
            /** Public Id */
            public_id: string;
            /** Published At */
            published_at: string | null;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            /** Summary */
            summary?: string | null;
            /** Tags */
            tags: string[];
            /** Text Source */
            text_source: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /** Why Saved */
            why_saved: string | null;
        };
        /** LibraryPageResponse */
        LibraryPageResponse: {
            /** Is True First Empty */
            is_true_first_empty: boolean;
            /** Items */
            items: components["schemas"]["LibraryItemResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** TranscriptBlockResponse */
        TranscriptBlockResponse: {
            /** End Sec */
            end_sec: number;
            /** Ordinal */
            ordinal: number;
            /** Source Url */
            source_url: string;
            /** Start Sec */
            start_sec: number;
            /** Text */
            text: string;
        };
        /** TranscriptPageResponse */
        TranscriptPageResponse: {
            /** Blocks */
            blocks: components["schemas"]["TranscriptBlockResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhySavedRequest */
        WhySavedRequest: {
            /** Why Saved */
            why_saved?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_challenge_api_v1_auth_challenges_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailSessionResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_session_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    dispatch_api_v1_ingest_dispatches__dispatch_public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispatch_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_items_api_v1_library_items_get: {
        parameters: {
            query?: {
                search?: string | null;
                collection?: string | null;
                lifecycle?: ("archived" | "ready" | "needs_action" | "failed" | "processing" | "queued") | null;
                include_archived?: boolean;
                sort?: "saved_desc" | "saved_asc" | "title_asc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryPageResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    detail_api_v1_library_items__item_public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_api_v1_library_items__item_public_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhySavedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transcript_page_api_v1_library_items__item_public_id__transcript_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptPageResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    archive_api_v1_library_items__item_public_id__archive_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restore_api_v1_library_items__item_public_id__restore_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retry_api_v1_library_items__item_public_id__retry_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token": string;
            };
            path: {
                item_public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_batch_api_v1_library_items_batch_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSaveResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
